### ISSUE TITLE
Cloud Native Java/Graalvm

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/quickstart-openshift#1031]
Try to build into the standard Docker pattern.  If not, look into adapter the builder so a different tool isn't required.

Example from https://github.com/bcgov/nr-forest-client/pull/396/files
```
  build-backend:
    name: Backend Image Build
    env:
      COMPONENT: backend
      ZONE: ${{ github.event.number }}
      NAME: ghcr.io/${{ github.repository }}/backend:${{ github.event.number }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.0'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build App
        run: |
          cd backend
          chmod +x ./mvnw
          ./mvnw -Pnative clean spring-boot:build-image \
          -Dspring-boot.build-image.imageName="${{ env.NAME }}" \
          -Doci.revision=${{ github.event.number }} \
          -DskipTests \
          -Dtests.skip=true \
          -Dskip.unit.tests=true \
          -q
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pushing
        run: docker push ${{ env.NAME }}
```
