### ISSUE TITLE
Crunchy over Patroni?

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/quickstart-openshift#1372]
I'm liking the sound of Crunchy over Patroni.  Still early.

Setup and lots of ideas courtesy of @conbrad.

```
  - apiVersion: postgres-operator.crunchydata.com/v1beta1
    kind: PostgresCluster
    metadata:
      name: ${APP_NAME}-${SUFFIX}
    spec:
      image: artifacts.developer.gov.bc.ca/bcgov-docker-local/crunchy-postgres-gis:ubi8-14.7-3.2-0
      metadata:
        name: ${APP_NAME}-${SUFFIX}
        labels:
          app: ${APP_NAME}-${SUFFIX}
      users:
        - name: ${APP_NAME}-${SUFFIX}
          databases:
            - postgres
          options: "SUPERUSER"
      postgresVersion: 14
      instances:
        - name: tileserv
          replicas: 3
          dataVolumeClaimSpec:
            accessModes:
              - "ReadWriteOnce"
            resources:
              requests:
                storage: 5Gi
                cpu: 15m
                memory: 200Mi
              limits:
                cpu: 100m
                memory: 500Mi
            storageClassName: netapp-block-standard
          walVolumeClaimSpec:
            accessModes:
              - "ReadWriteOnce"
            resources:
              requests:
                storage: 2Gi
            storageClassName: netapp-block-standard
      backups:
        pgbackrest:
          image: artifacts.developer.gov.bc.ca/bcgov-docker-local/crunchy-pgbackrest:ubi8-2.41-4
          repos:
            - name: repo1
              volume:
                volumeClaimSpec:
                  accessModes:
                    - "ReadWriteOnce"
                  resources:
                    requests:
                      storage: 5Gi

```

**Comment by DerekRoberts** [comment]
https://github.com/bcgov/wps/blob/main/openshift/templates/tileserv/tileserv.yaml

https://access.crunchydata.com/documentation/postgres-operator/latest/tutorials/basic-setup

**Comment by DerekRoberts** [comment]
(comments also stolen)

Oh wow look at their upgrade path for major versions, so easy: https://access.crunchydata.com/documentation/postgres-operator/latest/guides/major-postgres-version-upgrade

Postgres Major Version Upgrade

[11:43 AM] Brady, Conor WLRS:EX

```

apiVersion: postgres-operator.crunchydata.com/v1beta1

kind: PGUpgrade

metadata:

  name: hippo-upgrade

spec:

  image: registry.developers.crunchydata.com/crunchydata/crunchy-upgrade:ubi8-5.4.2-0

  postgresClusterName: hippo

  fromPostgresVersion: 14

  toPostgresVersion: 15

```
