### ISSUE TITLE
Auto pr labelling/nagging

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/quickstart-openshift#59]
https://github.com/marketplace/actions/actions-ecosystem-add-labels

**Comment by paulushcgcj** [comment]
The [forest-client](https://github.com/bcgov/nr-forest-client) is using something like this on the new branches with the action actions/labeler like

```
  - name: Pull request size and stability labels
        uses: actions/labeler@v4
        continue-on-error: true
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
```

It will lookup for a file inside the **.workflow** folder called **labeler.yml** where you can define how it will identify labels. An example is:

```
github_actions:
  - .github/*

tests:
  - backend/src/test/**/*.java
  - frontend/cypress/**/*
  - frontend/src/tests/**/*.spec.ts

docker:
  - any: ['Dockerfile','dockerfile-entrypoint.sh']

configuration:
  - backend/src/main/**/configuration/*.java
  - backend/src/main/resources/**/*
  - backend/config/**/*
  - frontend/tsconfig*
  - frontend/vite*
  - frontend/*.json

openshift:
  - '**/openshift.*.yml'
```

It will then tag the PR when the file change matches the labeler file
