### ISSUE TITLE
Set defaults.shell for Actions

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/quickstart-openshift#977]
https://docs.github.com/en/actions/using-jobs/setting-default-values-for-jobs
```
defaults:
  run:
    shell: bash
    working-directory: scripts
```
